#pragma once

#define GLUE_MOUSE_BUTTON_1         0
#define GLUE_MOUSE_BUTTON_2         1
#define GLUE_MOUSE_BUTTON_3         2
#define GLUE_MOUSE_BUTTON_4         3
#define GLUE_MOUSE_BUTTON_5         4
#define GLUE_MOUSE_BUTTON_6         5
#define GLUE_MOUSE_BUTTON_7         6
#define GLUE_MOUSE_BUTTON_8         7
#define GLUE_MOUSE_BUTTON_LAST      GLUE_MOUSE_BUTTON_8
#define GLUE_MOUSE_BUTTON_LEFT      GLUE_MOUSE_BUTTON_1
#define GLUE_MOUSE_BUTTON_RIGHT     GLUE_MOUSE_BUTTON_2
#define GLUE_MOUSE_BUTTON_MIDDLE    GLUE_MOUSE_BUTTON_3